tags:
  name: Products
  description: Products retrieval

components:
  schema:
    Product:
      type: object
      properties:
        name:
          type: string
          required: true
        category:
          type: string
          required: true
        brand:
          type: string
          required: true
        price:
          type: number
        currency:
          type: string
          description: Currency in ISO 4217 alphabetic code format
        productUrl:
          type: string
        description:
          type: string
          required: true
        carbonFootprint:
          type: object
          properties:
            co2Emission:
              type: string
            unit:
              type: string
        durability:
          type: string
        recyclingInfo:
          type: string
        imageUrl:
          type: string
        ecoCertification:
          type: string
        ecoFriendly:
          type: boolean
    Discount:
      type: object
      properties:
        discountCode:
          type: string
        description:
          type: string
        validUntil:
          type: string
          format: date
        partnerBrand:
          type: string
        productRestrictions:
          type: string
        termsAndConditions:
          type: string
        url:
          type: string

/products:
  get:
    summary: Get all products
    tags: [Products]
    parameters:
      - in: query
        name: page
        schema:
          type: integer
          default: 1
        description: Page number
      - in: query
        name: limit
        schema:
          type: integer
          default: 10
        description: Number of posts per page
      - in: query
        name: category
        schema:
          type: string
        description: Product category
    responses:
      200:
        description: A list of products
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                limit:
                  type: integer
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/Product'
                total:
                  type: integer
                pages:
                  type: integer

/products/{id}:
  get:
    summary: Get a specific product
    tags: [Products]
    parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Product ID
    responses:
      200:
        description: The product
        content:
          application/json:
            schema:
              type: object
              $ref: "$/components/schemas/Product"
      404:
        description: Product not found

/products/discounts:
  get:
    summary: Get all available discounts
    tags: [Products]
    responses:
      200:
        description: A list of discounts
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "$/components/schemas/Discount"

/products/discounts/{id}:
  get:
    summary: Get a specific discount
    tags: [Products]
    parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Discount ID
    responses:
      200:
        description: The discount
        content:
          application/json:
            schema:
              type: object
              $ref: "$/components/schemas/Discount"
      404:
        description: Discount not found